broadinstitute/firecloud-orchestration

README.md, build.sbt, src/main/scala/org/broadinstitute/dsde/firecloud/MethodsClient.scala
Task: https://broadinstitute.atlassian.net/browse/DSDEEPB-660
This is a provisional implementation to document the headers and help unblock local development. There is a follow-up task to refactor this into a correct implementation:
https://broadinstitute.atlassian.net/browse/DSDEEPB-667
=> Adds CORS headers to orchestration layer

build.sbt
Note that this change will throw an error in Scala versions < 2.11.2.
=> Enforce java 8 in build.sbt

README.md, src/main/resources/application.conf, src/main/resources/configurations.conf, src/main/scala/org/broadinstitute/dsde/firecloud/FireCloudConfig.scala, src/test/resources/test.conf
This PR breaks out secrets into the `test.conf` and `application.conf` files and adds another configuration file where we can hold all of the custom endpoint paths. Support for new endpoint paths should be placed in `configurations.conf`
=> Support multiple configurations.

build.sbt
Incremental builds have been failing consistently for me. The error message is nearly identical to the one in this bug report:
https://issues.scala-lang.org/browse/SI-9356
Upgrading to 2.11.7 seems to fix the issue.
=> Bump Scala version

src/main/scala/org/broadinstitute/dsde/firecloud/EntityClient.scala
compile would previously show:
```
[info] Compiling 19 Scala sources to /Users/davidan/work/src/firecloud-orchestration/target/scala-2.11/classes...
[warn] /Users/davidan/work/src/firecloud-orchestration/src/main/scala/org/broadinstitute/dsde/firecloud/EntityClient.scala:113: match may not be exhaustive.
[warn] It would fail on the following input: Failure((x: Throwable forSome x not in Exception))
[warn]     Try(Await.result(pipeline(externalRequest), Duration.Inf)) match {
[warn]        ^
[warn] one warning found
[success] Total time: 11 s, completed Aug 12, 2015 10:47:31 AM
```
but now it doesn't.
=> change Exception to Throwable to eliminate compile warning

build.sbt, src/main/scala/org/broadinstitute/dsde/firecloud/core/GetEntitiesWithType.scala, src/main/scala/org/broadinstitute/dsde/firecloud/model/ModelJsonProtocol.scala, src/main/scala/org/broadinstitute/dsde/firecloud/service/EntityService.scala, src/test/scala/org/broadinstitute/dsde/firecloud/mock/MockWorkspaceServer.scala, src/test/scala/org/broadinstitute/dsde/firecloud/service/EntityServiceSpec.scala
Notes:
* This has been tested against Rawls-dev.
* There is a lot of entity information that comes back from rawls. This only captures the name and entity type. The model class can be expanded to capture more information if the UI requires it.
* Format of the response is a list of entity name and entity type for easy tabular display. This can be re-modeled into a map of type -> list of names if that is easier for the UI to work with.
This approach uses the aggregator pattern: http://doc.akka.io/docs/akka/snapshot/contrib/aggregator.html
This (https://github.com/NET-A-PORTER/spray-actor-per-request/blob/master/src/main/scala/com/netaporter/core/DummyAppCore.scala) is another pattern that we could use. It is part of the Per Request pattern which we are not currently using, but might at some …
=> Implement combined call for entities with type information

src/main/resources/application.conf
with @dmohs ' changes in #47, I think we're in a good place:
* if you want to affect logging for our own log messages in our classes, change in logback.xml
* if you want to affect akka's internal logging, change in application.conf
while this means there are two files that would need editing under different conditions, I think this is a clear and understandable separation.
This PR should change nothing functionally - everything will log as it did before. The changes just provide a template for what you _would_ change if you wanted to affect akka logging.
The changes to application.conf will need to get deployed to jenkins, etc. to truly complete this story.
=> template config for actor logging

src/main/scala/org/broadinstitute/dsde/firecloud/service/WorkspaceService.scala, src/test/resources/testfiles/tsv/ADD_PARTICIPANTS.txt, src/test/resources/testfiles/tsv/ADD_SAMPLES.txt, src/test/resources/testfiles/tsv/TEST_INVALID.txt, src/test/resources/testfiles/tsv/TEST_INVALID_COLUMNS.txt, src/test/resources/testfiles/tsv/UPDATE_SAMPLES.txt, src/test/scala/org/broadinstitute/dsde/firecloud/service/WorkspaceServiceSpec.scala
just a small PR to add some tsv files that can be used to test against the current spec. ultimately, the goal will be to have these test files used in some unit tests- that way we'll know immediately when the tsv spec is updated. also removed some old code related to importing entities with json, since we now use tsv
=> added test tsv files and removed importJSON related activities

build.sbt, src/main/resources/configurations.conf, src/main/resources/swagger/api-docs.yaml, src/main/scala/org/broadinstitute/dsde/firecloud/FireCloudConfig.scala, src/main/scala/org/broadinstitute/dsde/firecloud/FireCloudServiceActor.scala
The new version of Swagger prefers the definition to be all in one file. This is not ideal, but because the YAML syntax is compact, I think it's okay for now.
There are some TODOs for fixing stuff, but I think this is a good place for us to review/discuss.
I think this will work in prod with the transparent proxy, since I tested it locally, but because the environments are slightly different, it might not. I will monitor the deploy.
=> First pass at Swagger via YAML

src/main/resources/swagger/api-docs.yaml
For DSDEEPB-1088
Notes:
* I put these two services into the same "tag" so they show up together in the UI. 
* We should standardize on naming convention and capitalization. Agora capitalizes the endpoint descriptions, Rawls does not. As this is user-facing, I like the Agora approach better.
=> Add methods and configurations swagger yml

src/main/scala/org/broadinstitute/dsde/firecloud/EntityClient.scala, src/main/scala/org/broadinstitute/dsde/firecloud/HttpClient.scala, src/main/scala/org/broadinstitute/dsde/firecloud/core/GetEntitiesWithType.scala, src/main/scala/org/broadinstitute/dsde/firecloud/service/FireCloudRequestBuilding.scala, src/main/scala/org/broadinstitute/dsde/firecloud/service/FireCloudTransformers.scala, src/main/scala/org/broadinstitute/dsde/firecloud/service/WorkspaceService.scala, src/test/scala/org/broadinstitute/dsde/firecloud/mock/MockMethodsServer.scala, src/test/scala/org/broadinstitute/dsde/firecloud/mock/MockUtils.scala, src/test/scala/org/broadinstitute/dsde/firecloud/mock/MockWorkspaceServer.scala, src/test/scala/org/broadinstitute/dsde/firecloud/mock/ValidMethodConfigurationFromRepoCallback.scala, src/test/scala/org/broadinstitute/dsde/firecloud/service/EntityServiceSpec.scala, src/test/scala/org/broadinstitute/dsde/firecloud/service/MethodConfigurationServiceSpec.scala, src/test/scala/org/broadinstitute/dsde/firecloud/service/MethodsServiceSpec.scala, src/test/scala/org/broadinstitute/dsde/firecloud/service/SubmissionServiceSpec.scala, src/test/scala/org/broadinstitute/dsde/firecloud/service/WorkspaceServiceSpec.scala
DO NOT MERGE without the new Google/OAuth proxy in place, and without reading through this description fully.
This is a *theoretical* and *untested* change. I haven't had a chance to spin up the new OAuth proxy locally, and rawls/agora don't support the new OAuth proxy yet, so I have no idea if this works. It'll be up to you to try it and see.
The heart of this change is the new FireCloudRequestBuilder trait and its authHeaders function. This looks for auth headers in the incoming request and copies those headers to the outgoing request.
**TODO: verify this is looking for the correct headers.**
_Other teams, like rawls, may want a copy of this trait!_
Then, I've modified all our endpoints to remove handling of the OpenAM cookie and replace with a call to the authHeaders function.
Finally, …
=> DSDEEPB-958: pass on new Google/OAuth headers

src/main/scala/org/broadinstitute/dsde/firecloud/HttpClient.scala, src/main/scala/org/broadinstitute/dsde/firecloud/service/PerRequest.scala
This should eliminate all the "Explicitly set response header 'Date: Wed, 09 Sep 2015 22:11:12 GMT' is ignored, the spray-can HTTP layer sets this header automatically!" messages in the orchestration layer log.
=> DSDEEPB-1235: Move filtering of automatic headers from HttpClient to PerRequest

src/main/scala/org/broadinstitute/dsde/firecloud/model/Workspace.scala
Agora and Rawls are both now using an int for config snapshot id. Orchestration was still using a String. This fixes that incompatibility.
*importing configs still has problems* but this unblocks development of those other problems. After this change, when I try to import a config, I get an error
```
{
message: "Error parsing Method Repo response: Object is missing required member 'methodRepoMethod'"
}
```
Which I'm guessing is going to require some UI changes.
=> DSDEEPB-1164: change method config snapshot from String to Int

src/main/resources/application.conf, src/main/resources/swagger/api-docs.yaml, src/main/scala/org/broadinstitute/dsde/firecloud/FireCloudConfig.scala, src/main/scala/org/broadinstitute/dsde/firecloud/model/ModelJsonProtocol.scala, src/main/scala/org/broadinstitute/dsde/firecloud/model/Workspace.scala, src/main/scala/org/broadinstitute/dsde/firecloud/service/EntityService.scala
Orchestration pass-through to copy an entity from one workspace to another.
*Note*: Rawls is currently throwing exceptions for this endpoint and it is not usable with real data.
=> Passthrough API for copying entities from one workspace to another.

src/main/resources/swagger/api-docs.yaml, src/main/scala/org/broadinstitute/dsde/firecloud/service/WorkspaceService.scala
As of now (Thursday 8/1 at 3:05PM) Rawls has a pair of bugs, one that bombs no matter what and one that bombs when the source workspace has data in it.  Fixes for both are in review and should be merged soon.  However, this code should be correct.
=> Passthrough for workspace clone

src/main/resources/swagger/api-docs.yaml, src/main/scala/org/broadinstitute/dsde/firecloud/model/ModelJsonProtocol.scala, src/main/scala/org/broadinstitute/dsde/firecloud/model/Workspace.scala, src/test/scala/org/broadinstitute/dsde/firecloud/mock/MockWorkspaceServer.scala
DSDEEPB-1343 directs us to remove methodRepoConfig from MethodConfiguration.  This is the corresponding part for orchestration.
=> eliminate methodRepoConfig

src/main/scala/org/broadinstitute/dsde/firecloud/FireCloudConfig.scala, src/main/scala/org/broadinstitute/dsde/firecloud/service/EntityService.scala, src/test/scala/org/broadinstitute/dsde/firecloud/mock/MockWorkspaceServer.scala, src/test/scala/org/broadinstitute/dsde/firecloud/service/EntityServiceSpec.scala
Addresses:
* Entity Service Failure: https://broadinstitute.atlassian.net/browse/DSDEEPB-1458
* Entity Service Tests: https://broadinstitute.atlassian.net/browse/DSDEEPB-824
This PR takes a slightly different approach to mock server tests. I've removed the entity-with-type tests (which will be addressed in an upcoming PR) and instead added mock responses in the same test class that are called by the service.
=> Update entity service and tests

src/main/resources/swagger/api-docs.yaml, src/main/scala/org/broadinstitute/dsde/firecloud/service/FireCloudDirectives.scala, src/test/scala/org/broadinstitute/dsde/firecloud/service/FireCloudDirectivesSpec.scala
This addresses a bug that would cause an exception to be thrown if there were special characters in a resource name (i.e. a space in a workspace name). I'm not a regex expert so if somebody who is could double check my pattern, that would be great!
Also fixed a little thing in swagger that I noticed was inconsistent with the actual orchestration code.
Jira ticket: https://broadinstitute.atlassian.net/browse/DSDEEPB-1479
=> encode uris to allow for spaces and other special characters in path

src/main/scala/org/broadinstitute/dsde/firecloud/service/FireCloudDirectives.scala, src/test/scala/org/broadinstitute/dsde/firecloud/service/FireCloudDirectivesSpec.scala
After #112 unit tests did not work, because they require local mock server URLs with ports in them, like `http://localhost:8989`
=> Allow port in URI to enable unit tests

src/main/resources/swagger/api-docs.yaml, src/main/scala/org/broadinstitute/dsde/firecloud/core/ExportEntitiesByType.scala, src/main/scala/org/broadinstitute/dsde/firecloud/service/EntityService.scala, src/main/scala/org/broadinstitute/dsde/firecloud/utils/EntityMatrix.scala, src/test/scala/org/broadinstitute/dsde/firecloud/service/ExportEntitiesByTypeServiceSpec.scala
This PR addresses exporting entities as a TSV file from the Orchestration layer: https://broadinstitute.atlassian.net/browse/DSDEEPB-1148
Notes:
* This does not fulfill all requirements of DSDEEPB-1148. If you take this PR, do not move the story along as there still needs to be a UI component to invoke this endpoint.
* Please look closely at EntityMatrix. As a class, it feels a bit more like java than scala and feedback on construction/implementation would be very much appreciated.
* I split out tests for this separately from EntityService due to the specialized nature of what it's doing.
* There are three cases of data conversion that happen on import and need to be reversed on export. participant_id, case_sample, and control_sample columns require special processing.
* I have not been …
=> Implement orchestration call for export entities by type

src/main/resources/application.conf, src/main/scala/org/broadinstitute/dsde/firecloud/FireCloudConfig.scala, src/main/scala/org/broadinstitute/dsde/firecloud/service/SubmissionService.scala, src/main/scala/org/broadinstitute/dsde/firecloud/service/WorkspaceService.scala, src/test/scala/org/broadinstitute/dsde/firecloud/mock/MockWorkspaceServer.scala, src/test/scala/org/broadinstitute/dsde/firecloud/service/EntitiesWithTypeServiceSpec.scala, src/test/scala/org/broadinstitute/dsde/firecloud/service/EntityServiceSpec.scala, src/test/scala/org/broadinstitute/dsde/firecloud/service/SubmissionServiceSpec.scala
All rawls endpoints move under /api for protection. This involved some cleanup and consolidation of hardcoded endpoints into application.conf.
=> DSDEEPB-1592: Move all rawls endpoints under /api

src/main/resources/swagger/api-docs.yaml, src/main/scala/org/broadinstitute/dsde/firecloud/service/WorkspaceService.scala
* Add swagger api doc for missing create call.
* Remove the custom handling of create workspace in favor or using a passthrough request. It was doing unnecessary things that Rawls is now handling correctly.
=> Update workspace service

src/main/resources/model.json, src/test/scala/org/broadinstitute/dsde/firecloud/utils/TSVParserSpec.scala
For https://broadinstitute.atlassian.net/browse/DSDEEPB-1457.
Remove _id from the end of all column keys, which are specified in the TSV spec: https://docs.google.com/document/d/1iBhW0LwrJYBihQw0qa0c-6hc3kd_mnOqlUlvghlxVMs
=> remove _id from all column keys in imported TSV

src/main/resources/application.conf, src/main/scala/org/broadinstitute/dsde/firecloud/FireCloudConfig.scala, src/test/scala/org/broadinstitute/dsde/firecloud/mock/MockMethodsServer.scala
I *think* this fixes everything. However, it's hard to test by clicking through the UI, because sometimes our communication with agora goes through rawls, and rawls isn't updated yet.
=> DSDEEPB-1708: move Agora urls under /api/v1

src/main/resources/swagger/api-docs.yaml, src/main/scala/org/broadinstitute/dsde/firecloud/FireCloudServiceActor.scala, src/main/scala/org/broadinstitute/dsde/firecloud/service/PerRequest.scala, src/main/scala/org/broadinstitute/dsde/firecloud/service/StorageService.scala
Create an endpoint within orchestration that contacts GCS to get info about a file, in support of downloading that file (or checking its existence, etc).
See https://cloud.google.com/storage/docs/json_api/v1/objects/get for details of the API.
UI can safely call the orchestration mirror via ajax without any CORS issues.
Remember you can browse GCS via their console, here: https://console.developers.google.com/project/broad-dsde-dev/storage/browser.
A few safe files you can use for manual testing (please don't delete these from GCS):
https://console.developers.google.com/project/broad-dsde-dev/storage/browser/bossdev/vault/test/
Note that it looks like this call returns a **safer** download url than the one we're generating in the UI. Because Google generates the download url instead of us …
=> DSDEEPB-660: Mirror for GCS get-metadata call to help with downloads

src/main/scala/org/broadinstitute/dsde/firecloud/core/GetEntitiesWithType.scala, src/main/scala/org/broadinstitute/dsde/firecloud/service/FireCloudDirectives.scala
@MatthewBemis - Let me know what you think about this approach. I move the encode method so it was easier to call from classes that don't work closely with PerRequest and used the encode method on url construction just to be safe.
=> Move encode to object and use in GetEntitiesWithType url construction

src/main/scala/org/broadinstitute/dsde/firecloud/core/GetEntitiesWithType.scala, src/main/scala/org/broadinstitute/dsde/firecloud/service/EntityService.scala, src/main/scala/org/broadinstitute/dsde/firecloud/service/FireCloudDirectives.scala
Now you can load entities in workspaces that have fancy characters in their names
=> encode uris in GET entities_with_type

src/main/resources/application.conf
**This will not fix the bug for the end user** because we need a similar change in rawls. Once both changes are in, I _think_ this will fix it; we'll have to test empirically.
=> DSDEEPB-1730: increase spray's content-length limit to 50m

.coveralls.yml, .travis.yml, README.md, project/plugins.sbt
This is ready for review. 
* I have found that there are sporadic timeout issues when travis runs tests, especially when there are simultaneous runs triggered from a PR and a push. We need to look into ways to try and minimize that noise. 
* Notifications is turned off by default. I think having the notification checks clear in the PR is enough for a reviewer to determine status.
=> Add travis and coveralls support

src/main/scala/org/broadinstitute/dsde/firecloud/service/EntityService.scala
Does not complete the story of DSDEEPB-1148, but implements the new `encodeUri` functionality.
=> Make sure url is encoded for download entity feature

src/main/resources/application.conf
change spray.can.server.parsing, not spray.can.parsing when setting max Content-Length; see spray/spray#346.
=> DSDEEPB-1730 (rev 2): increase spray's content-length limit to 50m

src/main/scala/org/broadinstitute/dsde/firecloud/model/ErrorReport.scala, src/test/scala/org/broadinstitute/dsde/firecloud/service/ServiceSpec.scala
I find it a tad suspicious that this isn't causing unmarshalling errors, but it seems to work.
=> Change fields to match Rawls

src/main/scala/org/broadinstitute/dsde/firecloud/service/StorageService.scala
quick change to support GCS objects with slashes - i.e. "subdirectories" of buckets.
Note: this fixes a problem in orch. In UI testing, I saw this working with my own test cases, but NOT with the test case mentioned in DSDEEPB-1911. That may be a UI bug.
=> DSDEEPB-1911: allow GCS object names containing slashes

src/test/scala/org/broadinstitute/dsde/firecloud/service/ServiceSpec.scala
We have a test in Travis that fails most of the time but not all the time, and I have a gut feeling Travis is just being slow.
=> increase route test timeouts from 1 to 5 seconds to pass Travis.

README.md, build.sbt, project/plugins.sbt, src/main/config/docker-compose.yaml.ctmpl, src/main/scala/org/broadinstitute/dsde/firecloud/FireCloudConfig.scala, src/main/scala/org/broadinstitute/dsde/firecloud/FireCloudServiceActor.scala, src/main/scala/org/broadinstitute/dsde/firecloud/dataaccess/HttpGoogleServicesDAO.scala, src/main/scala/org/broadinstitute/dsde/firecloud/model/ModelJsonProtocol.scala, src/main/scala/org/broadinstitute/dsde/firecloud/model/OAuth.scala, src/main/scala/org/broadinstitute/dsde/firecloud/service/OAuthService.scala
ready-for-review implementation of OAuth in orchestration layer.
You will need to set up new env vars for this:
* FIRECLOUD_URL_ROOT: what's the base url for the UI? (https://firecloud.dsde-dev.broadinstitute.org or https://local.broadinstitute.org). We need this to cleanly redirect the browser.
* GOOGLE_SECRET_JSON: the json, as downloaded from Google Developers Console, representing the client id/secret in use.
These are set up for the dev environment, but will need to be configured in staging/alpha/etc before this code goes out there.
You'll also need to make sure your credentials as set up in Google have the FIRECLOUD_URL_ROOT as an allowed origin, and have FIRECLOUD_URL_ROOT/service/oauth2callback as an authorized redirect URI.
To test, go to …
=> DSDEEPB-1723: OAuth implementation in orchestration

src/main/scala/org/broadinstitute/dsde/firecloud/model/ModelJsonProtocol.scala, src/main/scala/org/broadinstitute/dsde/firecloud/model/OAuth.scala, src/main/scala/org/broadinstitute/dsde/firecloud/service/OAuthService.scala
with this PR:
* we *always* request a refresh token during login. This means that you'll *always* see the Google screen asking your permission. We have DSDEEPB-1759 as a follow-on story to make this more graceful.
* once we have a refresh token, we PUT it to rawls.
=> DSDEEPB-1757: store OAuth refresh tokens via rawls

src/main/resources/swagger/api-docs.yaml, src/main/scala/org/broadinstitute/dsde/firecloud/dataaccess/HttpGoogleServicesDAO.scala, src/main/scala/org/broadinstitute/dsde/firecloud/model/ModelJsonProtocol.scala, src/main/scala/org/broadinstitute/dsde/firecloud/model/OAuth.scala, src/main/scala/org/broadinstitute/dsde/firecloud/service/OAuthService.scala
Changes in this PR:
* swagger doc (via hack) for login endpoint
* "path" param, representing the user's current nav state, is now optional
* add new "prompt" param, controlling whether or not to force-request a refresh token. This satisfies DSDEEPB-1760; typical usage should omit this param and allow orchestration to use its default value
* add new "callback" param, controlling where the OAuth process should redirect to after successful auth. This allows an orchestration instance running in dev to redirect back to local.broadinstitute.org after authn - in turn, this allows developers to run a local UI instance talking to a dev orchestration instance.
* during the login dance, check with rawls for a cached refresh token. If one does not exist, or if the cached token is too old, restart …
=> allow login process to cross environments with whitelist check

Dockerfile, script/create-configs.sh, src/docker/run.sh
Minor Dockerfile cleanups.
run.sh now attempts to find the .jar file. If it does not find one, it runs sbt '~ reStart' so incremental building works on every file save.
./script/create-configs.sh creates the config files from vault and, without arguments, modifies the resulting configs so that local.broadinstitute.org points to the orchestration containers.
Tested both sbt reStart and .jar modes locally.
=> Tweaks to run orch locally for development

src/main/resources/swagger/api-docs.yaml, src/main/scala/org/broadinstitute/dsde/firecloud/FireCloudServiceActor.scala
I *think* this is what's needed to use swagger via DSDE's centralized swagger instance. Without deploying it to there, I can't know for sure (unless I set up a new JS harness just for testing, but I'd rather not do that). It's possible this will need revision later.
Sadly, swagger-ui has bugs (https://github.com/swagger-api/swagger-ui/issues/1517, https://github.com/swagger-api/swagger-ui/issues/1330) that prevent us from defining security once at the top level - we have to define it once for each endpoint. *sigh*
I have NOT tackled any changes to basePath (DSDEEPB-2069). This is only the work for centralized swagger.
=> DSDEEPB-1355: centralized swagger instance

src/main/scala/org/broadinstitute/dsde/firecloud/service/OAuthService.scala
one-word change. Discovered by Blue Team and discussed over email.
=> store refresh token to rawls, not access token

src/main/scala/org/broadinstitute/dsde/firecloud/service/FireCloudDirectives.scala
I'm not 100% solid on how the `passthroughAllPaths` directive works, but this seems to fix it and doesn't break the other usages.
=> DSDEEPB-2111: Unable to load workspaces with space in name

src/main/scala/org/broadinstitute/dsde/firecloud/core/ProfileClient.scala, src/main/scala/org/broadinstitute/dsde/firecloud/service/UserService.scala, src/main/scala/org/broadinstitute/dsde/firecloud/utils/TSVFormatter.scala, src/test/scala/org/broadinstitute/dsde/firecloud/service/UserServiceSpec.scala
* Trimmed down the TSV Formatter so that it doesn't need to use a mutable seq any longer
* Consolidate the use of the Rawls `/register/user' path since it is the same for get and post.
=> Minor refactoring

src/main/resources/application.conf
See http://kamon.io/teamblog/2014/11/02/understanding-spray-client-timeout-settings/ and http://spray.io/documentation/1.2.3/spray-can/configuration/ for explanations. Goal of this is twofold:
1) increase timeouts for things like TSV uploads (DSDEEPB-1747). I don't think the timeouts will be completely addressed by this change, because we also need changes to Apache proxy timeouts.
2) increase performance under simultaneous load a bit, by allowing more simultaneous connections to rawls.
=> tweak spray client timeout/connection params

src/main/resources/swagger/api-docs.yaml, src/main/scala/org/broadinstitute/dsde/firecloud/FireCloudServiceActor.scala
This fixes local swagger for me. When we (I) added securityDefinitions for oauth, it broke token-injection. This should fix that.
=> add Bearer token into swagger securityDefinitions

src/main/config/firecloud-orchestration-compose.yaml.ctmpl
In Vault, I've added the signing key to the new common location for local and dev. I've also removed it from local, but NOT from dev (need to coordinate with the shib service before removing it there)
=> move shibboleth signing secret in vault

src/main/resources/application.conf
this does not fully fix the issue for the end user.
There was a simple misconfiguration in our application.conf - previously, I was trying to set spray.can.spray.can.client timeouts, not spray.can.client.
After this change is in place, the bug in question now gets 504 timeouts after 60 seconds. This is probably a timeout from the Apache proxy and needs to be fixed by devops - but this PR is a prerequisite.
=> fix misconfiguration in application.conf timeouts

src/main/scala/org/broadinstitute/dsde/firecloud/core/ProfileClient.scala, src/main/scala/org/broadinstitute/dsde/firecloud/dataaccess/HttpGoogleServicesDAO.scala, src/main/scala/org/broadinstitute/dsde/firecloud/model/ModelJsonProtocol.scala, src/main/scala/org/broadinstitute/dsde/firecloud/model/OAuth.scala, src/main/scala/org/broadinstitute/dsde/firecloud/model/Profile.scala, src/main/scala/org/broadinstitute/dsde/firecloud/service/OAuthService.scala, src/main/scala/org/broadinstitute/dsde/firecloud/utils/DateUtils.scala, src/test/scala/org/broadinstitute/dsde/firecloud/service/NIHServiceSpec.scala
When logging in to FireCloud, if the current user:
* has a linked NIH account
* has not re-linked with NIH within the last 24 hours
* has a NIH link expiration of more than 24 hours
then set the user's NIH link expiration to be 24 hours.
The implementation of this PR is, at first glance (and maybe the fifth glance), unconventional. The OAuth login would need to query Thurloe for NIH link keys, then inspect those keys and act appropriately. We already had an endpoint that queried and inspected those keys ... so I added the check-for-expiration feature into that code path. I like this approach also because it makes it trivially easy to enable the check-for-expiration feature in the /api/nih/status endpoint; in turn this may make it easy to call the check more often.
ProfileClient.scala has …
=> DSDEEPB-2403: FireCloud OAuth login updates NIH link expiration time

src/main/resources/swagger/api-docs.yaml, src/main/scala/org/broadinstitute/dsde/firecloud/model/ModelJsonProtocol.scala, src/main/scala/org/broadinstitute/dsde/firecloud/model/UserInfo.scala, src/main/scala/org/broadinstitute/dsde/firecloud/service/UserService.scala, src/test/scala/org/broadinstitute/dsde/firecloud/service/UserServiceSpec.scala
In support of the UI's checking/handling of user auth/registration status, this adds an endpoint at /me (i.e. /service/me) that:
* always returns json
* always returns 200, 401, 403, 404, or 500
Hopefully this helps keep the UI implementation simpler.
This is a proof-of-concept PR and I'm expecting folks might have feedback!
=> add a stable 'me' endpoint for checking user status

src/main/scala/org/broadinstitute/dsde/firecloud/core/ProfileClient.scala, src/main/scala/org/broadinstitute/dsde/firecloud/model/Profile.scala
now, when we save a profile to Thurloe, we store a version number instead of a true/false indicator. This allows us to change the profile fields over time.
=> DSDEEPB-2248: use version number for Thurloe profile instead of true/false

src/main/resources/application.conf, src/main/scala/org/broadinstitute/dsde/firecloud/core/ProfileClient.scala, src/main/scala/org/broadinstitute/dsde/firecloud/service/NIHService.scala, src/main/scala/org/broadinstitute/dsde/firecloud/service/NIHSyncService.scala, src/test/scala/org/broadinstitute/dsde/firecloud/service/NIHSyncEndpointsSpec.scala
I have now tested functionality locally, and this is ready for review. This PR adds a feature such that when a user successfully links an account to NIH, if the user exists on the current version of the whitelist, the user is immediately granted TCGA access.
This is purely additive. This does NOT remove the user from TCGA access in the corner case where the user previously had access, re-links an account, but is no longer on the current whitelist. In that case, the user will be removed the next time the scheduled sync-the-entire-whitelist process runs.
Testing this is somewhat difficult, especially if you do not have admin access directly to rawls. You will have to:
* manually update the whitelist file (see the fully-rendered firecloud-orchestration-compose for the location of that) to …
=> DSDEEPB-2395: grant access to NIH users immediately upon link

src/main/config/proxy-compose.yaml.ctmpl
This is required for 1/20 FireCloud launch, based on security scans of the FC system.
Previously, the proxy used an anonymous connection to the LDAP server for authorization. We need to use a credential to talk to LDAP instead; this PR makes that happen.
=> Add authenticated LDAP to proxy config
