src/main/scala/org/broadinstitute/dsde/firecloud/FireCloudConfig.scala, src/main/scala/org/broadinstitute/dsde/firecloud/MethodsClient.scala, src/main/scala/org/broadinstitute/dsde/firecloud/WorkspaceClient.scala, src/main/scala/org/broadinstitute/dsde/firecloud/service/MethodsService.scala, src/main/scala/org/broadinstitute/dsde/firecloud/service/ServiceUtils.scala, src/main/scala/org/broadinstitute/dsde/firecloud/service/WorkspaceService.scala, src/test/scala/org/broadinstitute/dsde/firecloud/MockServers.scala, src/test/scala/org/broadinstitute/dsde/firecloud/ValidWorkspaceCallback.scala, src/test/scala/org/broadinstitute/dsde/firecloud/service/WorkspaceServiceSpec.scala
Also factors out some of the CORS stuff.
=> Add list workspaces method

src/main/scala/org/broadinstitute/dsde/firecloud/EntityClient.scala
Hotfix for compilation error on master
=> Fix entity client

src/main/scala/org/broadinstitute/dsde/firecloud/model/ModelJsonProtocol.scala, src/main/scala/org/broadinstitute/dsde/firecloud/model/Workspace.scala, src/main/scala/org/broadinstitute/dsde/firecloud/service/WorkspaceService.scala, src/test/scala/org/broadinstitute/dsde/firecloud/service/WorkspaceServiceSpec.scala
The first part of [DSDEEPB-814](https://broadinstitute.atlassian.net/browse/DSDEEPB-814).
=> Receiving multipart form data from firecloud-ui to create entities from JSON

src/main/scala/org/broadinstitute/dsde/firecloud/EntityClient.scala, src/main/scala/org/broadinstitute/dsde/firecloud/model/ModelJsonProtocol.scala, src/main/scala/org/broadinstitute/dsde/firecloud/model/Workspace.scala, src/main/scala/org/broadinstitute/dsde/firecloud/service/WorkspaceService.scala, src/test/resources/test.conf, src/test/scala/org/broadinstitute/dsde/firecloud/MockServers.scala, src/test/scala/org/broadinstitute/dsde/firecloud/service/WorkspaceServiceSpec.scala
Temporary upload entities solution. This code will be refactored in the next sprint.
=> Batch upload entities to Rawls

src/main/resources/application.conf, src/test/resources/test.conf
swagger to build the wrong calls
=> Change swagger baseUrl to be at "" rather than "/api" which was causing

src/main/scala/org/broadinstitute/dsde/firecloud/service/MethodConfigurationService.scala, src/main/scala/org/broadinstitute/dsde/firecloud/service/WorkspaceService.scala
I will also take a stab at the tests this morning.
=> Move to MethodConfigurationService

src/main/scala/org/broadinstitute/dsde/firecloud/service/MethodConfigurationService.scala, src/main/scala/org/broadinstitute/dsde/firecloud/service/WorkspaceService.scala
This is the endpoint for updating a method configuration inside a workspace.
=> Our endpoint, sans tests

src/main/resources/configurations.conf, src/main/scala/org/broadinstitute/dsde/firecloud/FireCloudConfig.scala, src/main/scala/org/broadinstitute/dsde/firecloud/model/WorkspaceName.scala, src/main/scala/org/broadinstitute/dsde/firecloud/service/MethodConfigurationService.scala, src/test/scala/org/broadinstitute/dsde/firecloud/mock/MockWorkspaceServer.scala
I was getting some form of success with this.  Please carefully review though, this is the first I've really mucked with this codebase.
=> Updated model to match rawls change, added proper update path

src/main/scala/org/broadinstitute/dsde/firecloud/service/MethodsService.scala
It was already broken and not visible to the API. Follows decision from retro and is related to DSDEEPB-988
=> Remove swagger from the methods service

src/main/scala/org/broadinstitute/dsde/firecloud/EntityClient.scala, src/main/scala/org/broadinstitute/dsde/firecloud/FireCloudConfig.scala, src/main/scala/org/broadinstitute/dsde/firecloud/service/WorkspaceService.scala, src/test/scala/org/broadinstitute/dsde/firecloud/mock/MockTSV.scala, src/test/scala/org/broadinstitute/dsde/firecloud/mock/MockWorkspaceServer.scala, src/test/scala/org/broadinstitute/dsde/firecloud/service/WorkspaceServiceSpec.scala
Added distinction between membership, entity and update TSVs + refactor and tests.
As per DSDEEPB-937.
=> TSV types: membership, entity, and update

src/main/resources/configurations.conf
Please see this google doc for additional motivations of this change/commit/PR
https://docs.google.com/document/d/1EAsy6kiurP35nB3H9Mpq-mXOSUF2lDGcl__lLL65Ueg/edit
This PR is coupled with DSDEEPB-910 which is a subtask of DSDEEPB-506 which is currently high priority.
=> change in configurations path to get payload

src/main/resources/configurations.conf
the path change (include payload) although
includes the payload, it removes information
that we DO want (chet says we want it)
and that we DON'T want the payload!
=> sorry but I have to undo the earlier path change!

src/main/resources/configurations.conf, src/main/scala/org/broadinstitute/dsde/firecloud/FireCloudConfig.scala, src/main/scala/org/broadinstitute/dsde/firecloud/service/SubmissionService.scala
=> Passthrough to Rawls to get workflow outputs from a submission

src/main/scala/org/broadinstitute/dsde/firecloud/service/MethodConfigurationService.scala, src/test/scala/org/broadinstitute/dsde/firecloud/mock/MockWorkspaceServer.scala, src/test/scala/org/broadinstitute/dsde/firecloud/service/MethodConfigurationServiceSpec.scala
=> Orchestration support for removing a workspace method config

src/main/resources/swagger/api-docs.yaml
For DSDEEPB-1089
Notes:
* This was a bit more complicated as it required defining the expected SubmissionIngest json as an object in the yaml.
=> Add swagger yml for submission services

src/main/resources/swagger/api-docs.yaml, src/main/scala/org/broadinstitute/dsde/firecloud/service/EntityService.scala
=> Add entity service calls to swagger yml and clean up entity service.

src/main/resources/swagger/api-docs.yaml, src/main/scala/org/broadinstitute/dsde/firecloud/FireCloudException.scala, src/main/scala/org/broadinstitute/dsde/firecloud/HttpClient.scala, src/main/scala/org/broadinstitute/dsde/firecloud/core/GetEntitiesWithType.scala, src/main/scala/org/broadinstitute/dsde/firecloud/service/EntityService.scala, src/main/scala/org/broadinstitute/dsde/firecloud/service/MethodConfigurationService.scala, src/main/scala/org/broadinstitute/dsde/firecloud/service/MethodsService.scala, src/main/scala/org/broadinstitute/dsde/firecloud/service/PerRequest.scala, src/main/scala/org/broadinstitute/dsde/firecloud/service/SubmissionService.scala, src/main/scala/org/broadinstitute/dsde/firecloud/service/WorkspaceService.scala
I feel like I'm missing something. This implements the PerRequest pattern, as spearheaded by rawls and agora ... but it doesn't change a whole lot in the orchestration code? It does clean up the routes a little bit but not a lot.
=> DSDEEPB-979 PerRequest implementation

src/main/resources/swagger/api-docs.yaml, src/main/scala/org/broadinstitute/dsde/firecloud/service/MethodConfigurationService.scala
Creating a PR on @MattPutnam 's behalf for easier commenting
=> first pass

src/main/resources/swagger/api-docs.yaml, src/main/scala/org/broadinstitute/dsde/firecloud/service/SubmissionService.scala, src/test/scala/org/broadinstitute/dsde/firecloud/mock/MockWorkspaceServer.scala, src/test/scala/org/broadinstitute/dsde/firecloud/service/SubmissionServiceSpec.scala
=> added delete pass-through to  SubmissionService.scala

src/main/scala/org/broadinstitute/dsde/firecloud/FireCloudServiceActor.scala
Apache's ProxyPass includes this header explicitly for this purpose. Tested locally using modified script (watch for PR in firecloud-ui).
=> Use X-Forwarded-Host header when present for correct redirect URLs

src/main/resources/swagger/api-docs.yaml, src/main/scala/org/broadinstitute/dsde/firecloud/service/WorkspaceService.scala, src/test/scala/org/broadinstitute/dsde/firecloud/mock/MockWorkspaceServer.scala, src/test/scala/org/broadinstitute/dsde/firecloud/service/WorkspaceServiceSpec.scala
This is part of the UI work that Blue Team has taken on for [DSDEEPB-1137](https://broadinstitute.atlassian.net/browse/DSDEEPB-1137).
=> add patch endpoint for editing workspace attributes

src/main/scala/org/broadinstitute/dsde/firecloud/service/WorkspaceService.scala
Quick fix for something that didn't quite work with rawls in my previous PR
=> fixed updateAttributes endpoint

src/main/resources/model.json, src/main/scala/org/broadinstitute/dsde/firecloud/EntityClient.scala, src/main/scala/org/broadinstitute/dsde/firecloud/model/ModelJsonProtocol.scala, src/main/scala/org/broadinstitute/dsde/firecloud/model/ModelSchema.scala, src/test/scala/org/broadinstitute/dsde/firecloud/utils/TSVParserSpec.scala
=> allow for arbitrary renaming of TSV attributes as dictated by model.json

src/main/scala/org/broadinstitute/dsde/firecloud/FireCloudConfig.scala, src/main/scala/org/broadinstitute/dsde/firecloud/service/EntityService.scala, src/main/scala/org/broadinstitute/dsde/firecloud/service/FireCloudDirectives.scala, src/main/scala/org/broadinstitute/dsde/firecloud/service/MethodConfigurationService.scala, src/main/scala/org/broadinstitute/dsde/firecloud/service/MethodsService.scala, src/main/scala/org/broadinstitute/dsde/firecloud/service/StatusService.scala, src/main/scala/org/broadinstitute/dsde/firecloud/service/SubmissionService.scala, src/main/scala/org/broadinstitute/dsde/firecloud/service/WorkspaceService.scala, src/test/scala/org/broadinstitute/dsde/firecloud/mock/MockMethodsServer.scala
=> Enable all Agora services using generic passthrough

src/main/scala/org/broadinstitute/dsde/firecloud/service/FireCloudDirectives.scala
=> Need to account for query parameters

src/main/resources/application.conf, src/main/resources/swagger/api-docs.yaml, src/main/scala/org/broadinstitute/dsde/firecloud/FireCloudConfig.scala, src/main/scala/org/broadinstitute/dsde/firecloud/service/MethodConfigurationService.scala, src/main/scala/org/broadinstitute/dsde/firecloud/service/WorkspaceService.scala
* Method->config template
* Post config to workspace
* Get individual config details
Tested with live data
=> Added endpoints for method/config import/export

src/main/resources/swagger/api-docs.yaml, src/main/scala/org/broadinstitute/dsde/firecloud/model/ModelJsonProtocol.scala, src/main/scala/org/broadinstitute/dsde/firecloud/model/Workspace.scala, src/main/scala/org/broadinstitute/dsde/firecloud/service/EntityService.scala
Greg, this is what I'm thinking. This code is untested, but maybe it will give you a head start?
=> refactor of copy-entity API to reduce duplication of parameters

src/main/resources/swagger/api-docs.yaml, src/main/scala/org/broadinstitute/dsde/firecloud/core/GetEntitiesWithType.scala, src/test/scala/org/broadinstitute/dsde/firecloud/service/EntitiesWithTypeServiceSpec.scala
This PR addresses the GetEntitiesWithType actor swallowing errors:
https://broadinstitute.atlassian.net/browse/DSDEEPB-1420
Have added tests to ensure that the actor will fail fast when it encounters a downstream error.
=> Update actor, test, and api documentation

src/main/resources/application.conf, src/main/resources/swagger/api-docs.yaml, src/main/scala/org/broadinstitute/dsde/firecloud/FireCloudConfig.scala, src/main/scala/org/broadinstitute/dsde/firecloud/service/MethodConfigurationService.scala, src/test/scala/org/broadinstitute/dsde/firecloud/mock/MockWorkspaceServer.scala, src/test/scala/org/broadinstitute/dsde/firecloud/service/MethodConfigurationServiceSpec.scala
This is a PR for [DSDEEPB-511](https://broadinstitute.atlassian.net/browse/DSDEEPB-511).
There is a related PR in UI [here](https://github.com/broadinstitute/firecloud-ui/pull/213).
=> Passthrough for validating syntax of method configs

src/main/resources/swagger/api-docs.yaml, src/main/scala/org/broadinstitute/dsde/firecloud/service/WorkspaceService.scala
Also got rid of a bad tag I put on the create method template
=> Passthroughs for workspace lock/unlock

src/test/scala/org/broadinstitute/dsde/firecloud/service/ExportEntitiesByTypeServiceSpec.scala
=> Mock was missing authPrefix

src/main/resources/swagger/api-docs.yaml, src/main/scala/org/broadinstitute/dsde/firecloud/service/EntityService.scala
Passthrough all 3 endpoints at that path because why not, and document GET and DELETE.  Not swaggering PATCH for now because we're not using it (we're not using GET either but whatever).
=> Rawls passthrough for deleting entities

src/main/resources/swagger/api-docs.yaml, src/main/scala/org/broadinstitute/dsde/firecloud/core/DeleteEntities.scala, src/main/scala/org/broadinstitute/dsde/firecloud/core/GetEntitiesWithType.scala, src/main/scala/org/broadinstitute/dsde/firecloud/model/ModelJsonProtocol.scala, src/main/scala/org/broadinstitute/dsde/firecloud/model/Workspace.scala, src/main/scala/org/broadinstitute/dsde/firecloud/service/EntityService.scala
Also found a cosmetic error in the EntitiesWithType actor as I was referencing it.
=> Batch delete actor implemented

README.md, src/main/config/ca-bundle.crt.ctmpl, src/main/config/docker-compose.yaml.ctmpl, src/main/config/proxy-compose.yaml.ctmpl, src/main/config/server.crt.ctmpl, src/main/config/server.key.ctmpl
docs: https://github.com/broadinstitute/firecloud-environment
=> vault integration and docker compose

src/main/resources/swagger/api-docs.yaml, src/main/scala/org/broadinstitute/dsde/firecloud/core/AgoraPermissionHandler.scala, src/main/scala/org/broadinstitute/dsde/firecloud/model/MethodRepository.scala, src/main/scala/org/broadinstitute/dsde/firecloud/model/ModelJsonProtocol.scala, src/main/scala/org/broadinstitute/dsde/firecloud/service/MethodsService.scala, src/test/scala/org/broadinstitute/dsde/firecloud/mock/MockAgoraACLData.scala, src/test/scala/org/broadinstitute/dsde/firecloud/mock/MockAgoraACLServer.scala, src/test/scala/org/broadinstitute/dsde/firecloud/mock/ValidAgoraACLCallback.scala, src/test/scala/org/broadinstitute/dsde/firecloud/service/AgoraACLTranslationSpec.scala, src/test/scala/org/broadinstitute/dsde/firecloud/service/MethodsServiceACLSpec.scala, src/test/scala/org/broadinstitute/dsde/firecloud/service/MethodsServiceSpec.scala
See #123 - this is a clean version of that PR.
=> DSDEEPB-1414: Suport for FireCloud<->Agora ACL translations

src/main/resources/swagger/api-docs.yaml, src/main/scala/org/broadinstitute/dsde/firecloud/HttpClient.scala, src/main/scala/org/broadinstitute/dsde/firecloud/core/ProfileActor.scala, src/main/scala/org/broadinstitute/dsde/firecloud/model/ErrorReport.scala, src/main/scala/org/broadinstitute/dsde/firecloud/model/ModelJsonProtocol.scala, src/main/scala/org/broadinstitute/dsde/firecloud/model/Profile.scala, src/main/scala/org/broadinstitute/dsde/firecloud/service/FireCloudRequestBuilding.scala, src/main/scala/org/broadinstitute/dsde/firecloud/service/UserService.scala, src/test/scala/org/broadinstitute/dsde/firecloud/mock/MockUtils.scala, src/test/scala/org/broadinstitute/dsde/firecloud/service/UserServiceSpec.scala
Orchestration side of profile registration service. 
Parent story (https://broadinstitute.atlassian.net/browse/DSDEEPB-1815) is not complete without the UI side which is not implemented yet.
=> Profile registration service.

README.md, build.sbt, src/main/scala/org/broadinstitute/dsde/firecloud/model/Entity.scala, src/main/scala/org/broadinstitute/dsde/firecloud/model/ErrorReport.scala, src/main/scala/org/broadinstitute/dsde/firecloud/model/Workspace.scala
* Minor organization name refactor in build.sbt
* Remove unused swagger library in build.sbt
* Pulled in joda libraries that were needed after removing swagger
* Removed all swagger annotations from case classes
=> Post-swagger cleanup

src/main/resources/swagger/api-docs.yaml, src/main/scala/org/broadinstitute/dsde/firecloud/FireCloudServiceActor.scala, src/main/scala/org/broadinstitute/dsde/firecloud/service/UserService.scala, src/test/scala/org/broadinstitute/dsde/firecloud/service/UserServiceSpec.scala
This PR goes hand in hand with a UI component: https://github.com/broadinstitute/firecloud-ui/pull/284
=> Move profile endpoints under register.

src/main/config/ca-bundle.crt.ctmpl, src/main/config/docker-compose.yaml.ctmpl, src/main/config/proxy-compose.yaml.ctmpl, src/main/config/server.crt.ctmpl, src/main/config/server.key.ctmpl
Updated .ctmpl. WAIT for D Mohs to finish putting in the server.crt and server.key for dev and local into vault the proper way, with the value as "value".
=> Vault Update for .ctmpl

src/main/resources/swagger/api-docs.yaml, src/main/scala/org/broadinstitute/dsde/firecloud/service/UserService.scala
* passthrough to Google's userinfo endpoint, in support of DSDEEPB-1938 (this PR does not complete that story)
* passthrough to Rawls' billing info endpoints, in support of DSDEEPB-1494  (this PR does not complete that story)
=> DSDEEPB-1938, DSDEEPB-1494: orch passthroughs for billing projects, Google profile

src/main/scala/org/broadinstitute/dsde/firecloud/utils/TSVFormatter.scala
The code was only looking for certain known columns to try and deserialize. Updated so that it will always look and therefore handle any unknown cases.
=> Fix json deserialization problem.

src/main/scala/org/broadinstitute/dsde/firecloud/core/AgoraPermissionHandler.scala, src/main/scala/org/broadinstitute/dsde/firecloud/core/DeleteEntities.scala, src/main/scala/org/broadinstitute/dsde/firecloud/core/ExportEntitiesByType.scala, src/main/scala/org/broadinstitute/dsde/firecloud/core/GetEntitiesWithType.scala, src/main/scala/org/broadinstitute/dsde/firecloud/core/ProfileActor.scala
* Fix the close over sender problem (see http://helenaedelson.com/?p=879 for more details)
* Allow for PerRequest stop the child actors instead of explicitly stopping them.
* Implemented pipeTo pattern as per PR Feedback
=> Fix "close over sender" anti-pattern

src/main/resources/swagger/api-docs.yaml
I tried (and failed) to use the shorthand for the scope; this fixes it.
=> fix GCS scope for centralized swagger

src/main/scala/org/broadinstitute/dsde/firecloud/service/UserService.scala, src/test/scala/org/broadinstitute/dsde/firecloud/service/UserServiceSpec.scala
This is in support of DSDEEPB-2185 and is a minor update to support the needed UI functionality.
=> Passthrough for getting the Rawls version of user status

src/main/scala/org/broadinstitute/dsde/firecloud/core/ProfileClient.scala
This is in service of DSDEEPB-2247, though it doesn't solve that issue.
This goes with PR https://github.com/broadinstitute/firecloud-ui/pull/332.
This PR provides more detail in error reports during profile saving/checking user registration/registering users. I've tried to give a unique error string for each case, to help with bug reports from end users.
=> DSDEEPB-2247: detailed error reports for profile save/registration

src/main/config/firecloud-orchestration-compose.yaml.ctmpl
fix a regression from d5945a9153f71d400f1540be3ecf5dbae59e5a76.
=> use appropriate Vault value for google client id

build.sbt, src/main/config/firecloud-orchestration-compose.yaml.ctmpl, src/main/resources/swagger/api-docs.yaml, src/main/scala/org/broadinstitute/dsde/firecloud/FireCloudConfig.scala, src/main/scala/org/broadinstitute/dsde/firecloud/FireCloudServiceActor.scala, src/main/scala/org/broadinstitute/dsde/firecloud/core/ProfileClient.scala, src/main/scala/org/broadinstitute/dsde/firecloud/model/JWT.scala, src/main/scala/org/broadinstitute/dsde/firecloud/model/ModelJsonProtocol.scala, src/main/scala/org/broadinstitute/dsde/firecloud/model/Profile.scala, src/main/scala/org/broadinstitute/dsde/firecloud/service/NIHService.scala
This adds an endpoint at /api/nih/callback that accepts a JWT, then:
* validates the JWT
* extracts the NIH username from the JWT
* records the current time and NIH username in the user's profile
=> DSDEEPB-1926, DSDEEPB-2279: JWT from NIH

src/main/config/firecloud-orchestration-compose.yaml.ctmpl, src/main/scala/org/broadinstitute/dsde/firecloud/FireCloudConfig.scala
- Docker Compose environment variables
- Orchestration config
DSDEEPB-2371
=> Add admin refresh token

build.sbt, src/main/config/firecloud-account.pem.ctmpl, src/main/config/firecloud-orchestration-compose.yaml.ctmpl, src/main/resources/application.conf, src/main/resources/swagger/api-docs.yaml, src/main/scala/org/broadinstitute/dsde/firecloud/FireCloudConfig.scala, src/main/scala/org/broadinstitute/dsde/firecloud/FireCloudServiceActor.scala, src/main/scala/org/broadinstitute/dsde/firecloud/core/ProfileClient.scala, src/main/scala/org/broadinstitute/dsde/firecloud/dataaccess/HttpGoogleServicesDAO.scala, src/main/scala/org/broadinstitute/dsde/firecloud/model/ModelJsonProtocol.scala, src/main/scala/org/broadinstitute/dsde/firecloud/model/Workspace.scala, src/main/scala/org/broadinstitute/dsde/firecloud/service/FireCloudRequestBuilding.scala, src/main/scala/org/broadinstitute/dsde/firecloud/service/NIHService.scala, src/main/scala/org/broadinstitute/dsde/firecloud/service/NIHSyncService.scala, src/main/scala/org/broadinstitute/dsde/firecloud/service/UserService.scala, src/test/scala/org/broadinstitute/dsde/firecloud/service/NIHServiceSpec.scala, src/test/scala/org/broadinstitute/dsde/firecloud/service/NIHWhitelistSpec.scala
~~Please comment but note that it is completely untested.~~
~~The main commit is "nih/sync endpoint to sync the NIH TCGA/DBGAP whitelist" and the others all involve setting config files.~~
DSDEEPB-2384
=> nih/sync endpoint to sync the NIH TCGA/DBGAP whitelist

src/main/scala/org/broadinstitute/dsde/firecloud/model/ModelJsonProtocol.scala, src/main/scala/org/broadinstitute/dsde/firecloud/model/Profile.scala, src/test/scala/org/broadinstitute/dsde/firecloud/service/NIHServiceSpec.scala, src/test/scala/org/broadinstitute/dsde/firecloud/service/UserServiceSpec.scala
This requires UI work in this PR: https://github.com/broadinstitute/firecloud-ui/pull/369
=> Orchestration work for adding new fields to the profile page
